services:
  - type: web
    name: india-flash-news
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --pythonpath backend index:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: NEWS_API_KEY
        sync: false # User will provide this or it will be read from .env if uploaded
      - key: FLASK_DEBUG
        value: "false"
